// GENERATED by scripts/translate-policies.ts — DO NOT EDIT BY HAND except
// for reviewed accuracy fixes. English is the binding original (docs/00 D18);
// non-EN entries are DeepL machine translations, reviewed once. Regenerate:
//   set -a; source .env.local; set +a; npx tsx scripts/translate-policies.ts
import type { Locale } from './locales'
import type { PolicyDoc } from './policy-content'

export interface LocalizedDoc {
  title: string
  sections: { heading?: string; paragraphs: string[] }[]
}

export const POLICY_I18N: Record<Locale, Record<PolicyDoc['slug'], LocalizedDoc>> =
{
  "en": {
    "terms": {
      "title": "Terms of Service",
      "sections": [
        {
          "heading": "1. What this is",
          "paragraphs": [
            "One Tribe is an unofficial, non-commercial fan project — a shared memory archive for the hard-dance community. It is not affiliated with, endorsed by, or connected to Q-dance, Defqon.1, or any festival, artist, or label."
          ]
        },
        {
          "heading": "2. Your content",
          "paragraphs": [
            "When you upload a photo or GIF, or link a video (\"Memory\"), you confirm that: you captured it yourself and hold the rights to share it; it was taken at a music event you attended; you grant One Tribe a non-exclusive, worldwide, royalty-free license to host, display, resize, and translate its caption, solely to operate this site.",
            "You keep ownership. You can delete your Memory at any time using your deletion link."
          ]
        },
        {
          "heading": "3. What you may not upload",
          "paragraphs": [
            "Content you didn’t capture; full-song continuous recordings of performances (\"set rips\"); official media (aftermovies, pro photos, broadcast captures); NSFW or sexualized content; content focused on minors; AI-generated or manipulated images presented as real moments; spam or ads; content mocking or demeaning identifiable people."
          ]
        },
        {
          "heading": "4. Moderation",
          "paragraphs": [
            "Uploads appear on the wall immediately. We review recent uploads and reports after publication, and may hide or remove any content at our discretion. We honor rights-holder and privacy requests quickly (see takedown), and every Memory has a report link."
          ]
        },
        {
          "heading": "5. No warranty; limitation",
          "paragraphs": [
            "The site is provided \"as is\", free of charge. Voluntary donations only cover hosting costs and confer no benefits, features, or priority. To the maximum extent permitted by law, we accept no liability for damages arising from use of the site. Content reflects its uploaders, not the operator."
          ]
        },
        {
          "heading": "6. Changes; contact",
          "paragraphs": [
            "We may update these terms; continued use means acceptance. Contact: privacy@onetribe.world."
          ]
        }
      ]
    },
    "privacy": {
      "title": "Privacy Policy",
      "sections": [
        {
          "heading": "1. Who we are",
          "paragraphs": [
            "One Tribe (onetribe.world) is a non-commercial fan project operated from South Korea. Contact: privacy@onetribe.world."
          ]
        },
        {
          "heading": "2. What we collect",
          "paragraphs": [
            "Memories: photos/GIFs you upload and video links you embed, captions, event/city/year, an optional display name and social link. Published publicly immediately; may be hidden or removed on review or report.",
            "Account (optional): account ID (anonymous by default), display name, home country, festival attendance log (\"Passport\"), and — only if you choose to link them — your email address or Google account identity.",
            "Technical: privacy-friendly analytics (no cross-site tracking, no ad cookies), and logs needed to run the service.",
            "We do not run facial recognition or automatic tagging of people. We do not sell data."
          ]
        },
        {
          "heading": "3. People in crowd photos",
          "paragraphs": [
            "Festival photos may show other attendees. Our legal basis for publishing is legitimate interest in community documentation of public events, balanced against your rights.",
            "If you appear in a photo and want it removed or blurred, tell us — we will act within 48 hours, no questions asked: privacy@onetribe.world."
          ]
        },
        {
          "heading": "4. Your rights (GDPR)",
          "paragraphs": [
            "Access, rectification, erasure, restriction, objection, portability. You can delete your passport yourself on the passport page — your moments stay on the wall, anonymized, each with its own delete link. Email privacy@onetribe.world for anything else. You may also complain to your local data-protection authority."
          ]
        },
        {
          "heading": "5. Storage & processors",
          "paragraphs": [
            "Content is stored with our infrastructure providers (database/auth: Supabase; media: Cloudflare R2; translation: DeepL; sign-in emails: Resend). Captions are machine-translated; translated text is cached. Data may be processed in the EU and US under standard safeguards.",
            "Donations are processed off-site by Ko-fi and GitHub Sponsors; we receive no payment data."
          ]
        },
        {
          "heading": "6. Retention",
          "paragraphs": [
            "Published Memories stay until you delete them or a valid request removes them. Deleted content is purged from active systems within 30 days."
          ]
        },
        {
          "heading": "7. Minors",
          "paragraphs": [
            "The site is not directed at children. We blur or remove images focusing on minors on request or at our discretion."
          ]
        }
      ]
    },
    "takedown": {
      "title": "Copyright & Removal",
      "sections": [
        {
          "paragraphs": [
            "Removal requests — we keep this simple."
          ]
        },
        {
          "heading": "You uploaded it and want it gone?",
          "paragraphs": [
            "Use the deletion link you received, or email us — removed immediately."
          ]
        },
        {
          "heading": "You’re in a photo and don’t want to be?",
          "paragraphs": [
            "Email privacy@onetribe.world with the photo link. Removed or blurred within 48 hours, no questions asked."
          ]
        },
        {
          "heading": "You’re a rights holder",
          "paragraphs": [
            "(artist, label, festival, photographer): email privacy@onetribe.world with (1) the content link, (2) what you own, (3) your contact. We review promptly and remove valid claims — typically within 24–48 hours. Repeat infringers are blocked from uploading.",
            "Counter-notice: if your upload was removed and you believe it was a mistake, reply with an explanation; we may restore after review.",
            "We’re fans, not adversaries. If something bothers you, tell us and it comes down."
          ]
        }
      ]
    },
    "guidelines": {
      "title": "Community Guidelines",
      "sections": [
        {
          "heading": "Keep it yours.",
          "paragraphs": [
            "Only upload what you captured yourself."
          ]
        },
        {
          "heading": "Keep it real.",
          "paragraphs": [
            "Real moments only — no AI images, no official media rips."
          ]
        },
        {
          "heading": "Keep it short.",
          "paragraphs": [
            "Photos and GIFs — link a video instead of uploading it. No full-set recordings — support the artists."
          ]
        },
        {
          "heading": "Keep it kind.",
          "paragraphs": [
            "No mocking people, no NSFW, no hate symbols. If a stranger is the focus of your shot, imagine them seeing it."
          ]
        },
        {
          "heading": "Minors",
          "paragraphs": [
            "Don’t make kids the focus; we may blur."
          ]
        },
        {
          "heading": "Someone in your photo objects?",
          "paragraphs": [
            "They win. Always."
          ]
        }
      ]
    }
  },
  "nl": {
    "terms": {
      "title": "Gebruiksvoorwaarden",
      "sections": [
        {
          "heading": "1. Wat dit is",
          "paragraphs": [
            "One Tribe is een onofficieel, niet-commercieel fanproject — een gezamenlijk archief van herinneringen voor de hard-dance-gemeenschap. Het staat los van, wordt niet gesteund door en heeft geen banden met Q-dance, Defqon.1 of enig ander festival, artiest of label."
          ]
        },
        {
          "heading": "2. Je inhoud",
          "paragraphs": [
            "Wanneer je een foto of GIF uploadt, of een link naar een video plaatst (“Herinnering”), bevestig je dat: je deze zelf hebt gemaakt en de rechten hebt om deze te delen; deze is gemaakt tijdens een muziekevenement dat je hebt bijgewoond; je One Tribe een niet-exclusieve, wereldwijde, royaltyvrije licentie verleent om de foto te hosten, weer te geven, het formaat aan te passen en het bijschrift te vertalen, uitsluitend ten behoeve van de exploitatie van deze website.",
            "Je blijft eigenaar. Je kunt je Memory op elk moment verwijderen via de verwijderingslink."
          ]
        },
        {
          "heading": "3. Wat je niet mag uploaden",
          "paragraphs": [
            "Inhoud die je niet zelf hebt opgenomen; ononderbroken opnames van volledige nummers tijdens optredens (“set rips”); officiële media (aftermovies, professionele foto’s, opnames van uitzendingen); NSFW- of seksueel getinte inhoud; inhoud gericht op minderjarigen; door AI gegenereerde of gemanipuleerde beelden die worden gepresenteerd als echte momenten; spam of advertenties; inhoud waarin herkenbare personen worden bespot of vernederd."
          ]
        },
        {
          "heading": "4. Moderatie",
          "paragraphs": [
            "Uploads verschijnen direct op de tijdlijn. We beoordelen recente uploads en meldingen na publicatie en kunnen naar eigen goeddunken inhoud verbergen of verwijderen. We geven snel gevolg aan verzoeken van rechthebbenden en privacyverzoeken (zie ‘verwijdering’), en elke Memory heeft een meldingslink."
          ]
        },
        {
          "heading": "5. Geen garantie; beperking",
          "paragraphs": [
            "De website wordt gratis aangeboden „zoals hij is“. Vrijwillige donaties dekken uitsluitend de hostingkosten en leveren geen voordelen, extra functies of voorrang op. Voor zover wettelijk toegestaan, aanvaarden wij geen aansprakelijkheid voor schade die voortvloeit uit het gebruik van de website. De inhoud is afkomstig van de gebruikers die deze hebben geüpload, en niet van de beheerder."
          ]
        },
        {
          "heading": "6. Wijzigingen; contactgegevens",
          "paragraphs": [
            "We kunnen deze voorwaarden bijwerken; door het gebruik ervan te blijven maken, gaat u hiermee akkoord. Contact: privacy@onetribe.world."
          ]
        }
      ]
    },
    "privacy": {
      "title": "Privacybeleid",
      "sections": [
        {
          "heading": "1. Wie wij zijn",
          "paragraphs": [
            "One Tribe (onetribe.world) is een niet-commercieel fanproject dat vanuit Zuid-Korea wordt beheerd. Contact: privacy@onetribe.world."
          ]
        },
        {
          "heading": "2. Welke gegevens we verzamelen",
          "paragraphs": [
            "Herinneringen: foto’s/GIF’s die je uploadt en videolinks die je insluit, bijschriften, evenement/stad/jaar, een optionele weergavenaam en een link naar sociale media. Wordt onmiddellijk openbaar gepubliceerd; kan na beoordeling of na een melding worden verborgen of verwijderd.",
            "Account (optioneel): account-ID (standaard anoniem), weergavenaam, land van herkomst, festivalbezoeklogboek („Passport”) en — alleen als je ervoor kiest om deze te koppelen — je e-mailadres of Google-account.",
            "Technisch: privacyvriendelijke analyse (geen tracking tussen websites, geen advertentiecookies) en logbestanden die nodig zijn om de dienst te laten draaien.",
            "Wij maken geen gebruik van gezichtsherkenning of het automatisch taggen van personen. Wij verkopen geen gegevens."
          ]
        },
        {
          "heading": "3. Mensen op foto’s met een menigte",
          "paragraphs": [
            "Op festivalfoto’s kunnen andere bezoekers te zien zijn. Onze rechtsgrondslag voor het publiceren is het gerechtvaardigd belang bij het vastleggen van openbare evenementen ten behoeve van de gemeenschap, waarbij uw rechten in aanmerking worden genomen.",
            "Als je op een foto staat en je wilt dat deze wordt verwijderd of onherkenbaar wordt gemaakt, laat het ons dan weten — we zullen binnen 48 uur actie ondernemen, zonder vragen te stellen: privacy@onetribe.world."
          ]
        },
        {
          "heading": "4. Uw rechten (AVG)",
          "paragraphs": [
            "Toegang, rectificatie, verwijdering, beperking, bezwaar, overdraagbaarheid. Je kunt je paspoort zelf verwijderen op de paspoortpagina — je momenten blijven op de muur staan, geanonimiseerd, elk met een eigen verwijderlink. Stuur een e-mail naar privacy@onetribe.world voor overige zaken. Je kunt ook een klacht indienen bij je lokale gegevensbeschermingsautoriteit."
          ]
        },
        {
          "heading": "5. Opslag en verwerkers",
          "paragraphs": [
            "De inhoud wordt opgeslagen bij onze infrastructuurproviders (database/authenticatie: Supabase; media: Cloudflare R2; vertaling: DeepL; e-mails voor het aanmaken van een account: Resend). Ondertitels worden automatisch vertaald; de vertaalde tekst wordt in de cache opgeslagen. Gegevens kunnen in de EU en de VS worden verwerkt onder naleving van de standaardwaarborgen.",
            "Donaties worden extern verwerkt door Ko-fi en GitHub Sponsors; wij ontvangen geen betalingsgegevens."
          ]
        },
        {
          "heading": "6. Behoud",
          "paragraphs": [
            "Gepubliceerde herinneringen blijven staan totdat je ze verwijdert of totdat ze op basis van een geldig verzoek worden verwijderd. Verwijderde inhoud wordt binnen 30 dagen uit de actieve systemen gewist."
          ]
        },
        {
          "heading": "7. Minderjarigen",
          "paragraphs": [
            "De website is niet gericht op kinderen. Op verzoek of naar eigen goeddunken zullen wij afbeeldingen waarop minderjarigen te zien zijn, vervagen of verwijderen."
          ]
        }
      ]
    },
    "takedown": {
      "title": "Auteursrecht en verwijdering",
      "sections": [
        {
          "paragraphs": [
            "Verwijderingsverzoeken — wij houden het simpel."
          ]
        },
        {
          "heading": "Heb je het geüpload en wil je het nu weer verwijderen?",
          "paragraphs": [
            "Gebruik de verwijderingslink die je hebt ontvangen, of stuur ons een e-mail — dan wordt het onmiddellijk verwijderd."
          ]
        },
        {
          "heading": "Sta je op een foto en wil je daar niet op staan?",
          "paragraphs": [
            "Stuur een e-mail naar privacy@onetribe.world met de link naar de foto. De foto wordt binnen 48 uur verwijderd of onherkenbaar gemaakt, zonder dat er vragen worden gesteld."
          ]
        },
        {
          "heading": "U bent een rechthebbende",
          "paragraphs": [
            "(artiest, platenlabel, festival, fotograaf): stuur een e-mail naar privacy@onetribe.world met (1) de link naar de inhoud, (2) wat jouw eigendom is, (3) je contactgegevens. We beoordelen dit zo snel mogelijk en verwijderen gegronde claims — doorgaans binnen 24 tot 48 uur. Herhaaldelijke overtreders krijgen een uploadverbod.",
            "Tegenmelding: als je upload is verwijderd en je denkt dat dit ten onrechte is gebeurd, reageer dan met een toelichting; na beoordeling kunnen we de upload mogelijk weer herstellen.",
            "We zijn fans, geen tegenstanders. Als je ergens aanstoot aan neemt, laat het ons dan weten en dan wordt het verwijderd."
          ]
        }
      ]
    },
    "guidelines": {
      "title": "Richtlijnen voor de community",
      "sections": [
        {
          "heading": "Houd het voor jezelf.",
          "paragraphs": [
            "Upload alleen materiaal dat je zelf hebt opgenomen."
          ]
        },
        {
          "heading": "Blijf jezelf.",
          "paragraphs": [
            "Alleen echte momenten — geen AI-afbeeldingen, geen officiële media-uitknipsels."
          ]
        },
        {
          "heading": "Houd het kort.",
          "paragraphs": [
            "Foto’s en GIF’s — plaats een link naar een video in plaats van deze te uploaden. Geen volledige optredens — steun de artiesten."
          ]
        },
        {
          "heading": "Wees aardig.",
          "paragraphs": [
            "Geen spot met mensen, geen NSFW, geen haatsymbolen. Als een onbekende centraal staat in je foto, stel je dan voor dat diegene de foto ziet."
          ]
        },
        {
          "heading": "Minderjarigen",
          "paragraphs": [
            "Stel kinderen niet centraal; anders raken we misschien uit beeld."
          ]
        },
        {
          "heading": "Heeft iemand op je foto bezwaar?",
          "paragraphs": [
            "Zij winnen. Altijd."
          ]
        }
      ]
    }
  },
  "de": {
    "terms": {
      "title": "Nutzungsbedingungen",
      "sections": [
        {
          "heading": "1. Worum es sich dabei handelt",
          "paragraphs": [
            "„One Tribe“ ist ein inoffizielles, nichtkommerzielles Fanprojekt – ein gemeinsames Erinnerungsarchiv für die Hard-Dance-Community. Es steht in keiner Verbindung zu Q-dance, Defqon.1 oder anderen Festivals, Künstlern oder Labels und wird von diesen weder unterstützt noch empfohlen."
          ]
        },
        {
          "heading": "2. Ihre Inhalte",
          "paragraphs": [
            "Wenn Sie ein Foto oder ein GIF hochladen oder ein Video verlinken („Erinnerung“), bestätigen Sie, dass: Sie das Material selbst aufgenommen haben und über die Rechte zur Weitergabe verfügen; es bei einer Musikveranstaltung aufgenommen wurde, an der Sie teilgenommen haben; Sie gewähren One Tribe eine nicht-exklusive, weltweite, gebührenfreie Lizenz zum Hosten, Anzeigen, Anpassen der Größe und Übersetzen der Bildunterschrift, ausschließlich zum Zweck des Betriebs dieser Website.",
            "Sie behalten das Eigentumsrecht. Sie können Ihre „Memory“ jederzeit über Ihren Löschlink löschen."
          ]
        },
        {
          "heading": "3. Was Sie nicht hochladen dürfen",
          "paragraphs": [
            "Inhalte, die Sie nicht selbst aufgenommen haben; durchgehende Aufnahmen ganzer Songs von Auftritten („Set-Rips“); offizielle Medien (Aftermovies, professionelle Fotos, Ausschnitte aus Sendungen); NSFW- oder sexualisierte Inhalte; Inhalte, die sich auf Minderjährige konzentrieren; KI-generierte oder manipulierte Bilder, die als echte Momente präsentiert werden; Spam oder Werbung; Inhalte, die identifizierbare Personen verspotten oder herabwürdigen."
          ]
        },
        {
          "heading": "4. Moderation",
          "paragraphs": [
            "Hochgeladene Inhalte erscheinen sofort auf der Pinnwand. Wir prüfen aktuelle Uploads und Meldungen nach der Veröffentlichung und behalten uns vor, Inhalte nach eigenem Ermessen auszublenden oder zu entfernen. Wir kommen Anfragen von Rechteinhabern und Datenschutzanfragen umgehend nach (siehe „Takedown“), und jedes „Memory“ verfügt über einen Link zum Melden."
          ]
        },
        {
          "heading": "5. Keine Gewährleistung; Haftungsbeschränkung",
          "paragraphs": [
            "Die Website wird kostenlos und „wie besehen“ zur Verfügung gestellt. Freiwillige Spenden decken lediglich die Hosting-Kosten und begründen keinerlei Vorteile, Funktionen oder Vorrang. Soweit gesetzlich zulässig, übernehmen wir keine Haftung für Schäden, die durch die Nutzung der Website entstehen. Die Inhalte spiegeln die Ansichten der jeweiligen Urheber wider, nicht die des Betreibers."
          ]
        },
        {
          "heading": "6. Änderungen; Kontakt",
          "paragraphs": [
            "Wir behalten uns vor, diese Bedingungen zu aktualisieren; durch die fortgesetzte Nutzung erklären Sie sich damit einverstanden. Kontakt: privacy@onetribe.world."
          ]
        }
      ]
    },
    "privacy": {
      "title": "Datenschutzerklärung",
      "sections": [
        {
          "heading": "1. Wer wir sind",
          "paragraphs": [
            "One Tribe (onetribe.world) ist ein nichtkommerzielles Fanprojekt, das von Südkorea aus betrieben wird. Kontakt: privacy@onetribe.world."
          ]
        },
        {
          "heading": "2. Welche Daten wir erheben",
          "paragraphs": [
            "Erinnerungen: Fotos/GIFs, die Sie hochladen, sowie eingebettete Videolinks, Bildunterschriften, Veranstaltung/Stadt/Jahr, ein optionaler Anzeigename und ein Link zu sozialen Netzwerken. Werden sofort öffentlich veröffentlicht; können nach Überprüfung oder aufgrund einer Meldung ausgeblendet oder entfernt werden.",
            "Konto (optional): Konto-ID (standardmäßig anonym), Anzeigename, Heimatland, Festivalbesuchsprotokoll („Passport“) und – nur, wenn Sie sich dafür entscheiden, diese zu verknüpfen – Ihre E-Mail-Adresse oder Ihre Google-Konto-ID.",
            "Technische Aspekte: datenschutzfreundliche Analysen (kein webseitenübergreifendes Tracking, keine Werbe-Cookies) sowie Protokolle, die für den Betrieb des Dienstes erforderlich sind.",
            "Wir führen weder Gesichtserkennung noch automatische Personenmarkierung durch. Wir verkaufen keine Daten."
          ]
        },
        {
          "heading": "3. Personen auf Gruppenfotos",
          "paragraphs": [
            "Auf Festivalfotos sind möglicherweise andere Besucher zu sehen. Unsere Rechtsgrundlage für die Veröffentlichung ist das berechtigte Interesse an der Dokumentation öffentlicher Veranstaltungen durch die Gemeinschaft, abgewogen gegen Ihre Rechte.",
            "Wenn Sie auf einem Foto zu sehen sind und möchten, dass es entfernt oder unkenntlich gemacht wird, teilen Sie uns dies bitte mit – wir werden innerhalb von 48 Stunden handeln, ohne Fragen zu stellen: privacy@onetribe.world."
          ]
        },
        {
          "heading": "4. Ihre Rechte (DSGVO)",
          "paragraphs": [
            "Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch, Datenübertragbarkeit. Sie können Ihren Pass selbst auf der Pass-Seite löschen – Ihre Momente bleiben anonymisiert auf der Pinnwand erhalten, jeweils mit einem eigenen Löschlink. Bei weiteren Fragen senden Sie bitte eine E-Mail an privacy@onetribe.world. Sie können außerdem eine Beschwerde bei Ihrer örtlichen Datenschutzbehörde einreichen."
          ]
        },
        {
          "heading": "5. Speicher & Prozessoren",
          "paragraphs": [
            "Die Inhalte werden bei unseren Infrastrukturanbietern gespeichert (Datenbank/Authentifizierung: Supabase; Medien: Cloudflare R2; Übersetzung: DeepL; E-Mails zur Anmeldung: Resend). Bildunterschriften werden maschinell übersetzt; der übersetzte Text wird zwischengespeichert. Die Daten können unter Einhaltung der üblichen Sicherheitsvorkehrungen in der EU und den USA verarbeitet werden.",
            "Spenden werden extern von Ko-fi und GitHub Sponsors abgewickelt; wir erhalten keine Zahlungsdaten."
          ]
        },
        {
          "heading": "6. Kundenbindung",
          "paragraphs": [
            "Veröffentlichte Erinnerungen bleiben so lange bestehen, bis Sie sie löschen oder sie aufgrund einer gültigen Anfrage entfernt werden. Gelöschte Inhalte werden innerhalb von 30 Tagen aus den aktiven Systemen entfernt."
          ]
        },
        {
          "heading": "7. Minderjährige",
          "paragraphs": [
            "Die Website richtet sich nicht an Kinder. Auf Anfrage oder nach unserem Ermessen verwischen oder entfernen wir Bilder, auf denen Minderjährige zu sehen sind."
          ]
        }
      ]
    },
    "takedown": {
      "title": "Urheberrecht & Löschung",
      "sections": [
        {
          "paragraphs": [
            "Löschanträge – wir halten es einfach."
          ]
        },
        {
          "heading": "Du hast es hochgeladen und möchtest es jetzt wieder löschen?",
          "paragraphs": [
            "Nutzen Sie den Löschlink, den Sie erhalten haben, oder senden Sie uns eine E-Mail – der Eintrag wird umgehend gelöscht."
          ]
        },
        {
          "heading": "Du bist auf einem Foto zu sehen und möchtest das nicht?",
          "paragraphs": [
            "Senden Sie eine E-Mail an privacy@onetribe.world mit dem Link zum Foto. Das Foto wird innerhalb von 48 Stunden entfernt oder unkenntlich gemacht, ohne dass Fragen gestellt werden."
          ]
        },
        {
          "heading": "Sie sind Rechteinhaber",
          "paragraphs": [
            "(Künstler, Label, Festival, Fotograf): Senden Sie eine E-Mail an privacy@onetribe.world mit (1) dem Link zum Inhalt, (2) Angaben dazu, was Ihnen gehört, und (3) Ihren Kontaktdaten. Wir prüfen die Meldung umgehend und entfernen berechtigte Ansprüche – in der Regel innerhalb von 24 bis 48 Stunden. Wiederholungstäter werden für das Hochladen gesperrt.",
            "Widerspruch: Falls Ihr Beitrag entfernt wurde und Sie der Meinung sind, dass dies ein Irrtum war, antworten Sie bitte mit einer Erklärung; nach Prüfung werden wir den Beitrag möglicherweise wiederherstellen.",
            "Wir sind Fans, keine Gegner. Wenn dich etwas stört, sag es uns, und wir nehmen es runter."
          ]
        }
      ]
    },
    "guidelines": {
      "title": "Community-Richtlinien",
      "sections": [
        {
          "heading": "Behalte es für dich.",
          "paragraphs": [
            "Lade nur Inhalte hoch, die du selbst aufgenommen hast."
          ]
        },
        {
          "heading": "Bleib authentisch.",
          "paragraphs": [
            "Nur echte Momente – keine KI-Bilder, keine offiziellen Medienausschnitte."
          ]
        },
        {
          "heading": "Fass dich kurz.",
          "paragraphs": [
            "Fotos und GIFs – verlinke ein Video, anstatt es hochzuladen. Keine Aufnahmen der gesamten Show – unterstütze die Künstler."
          ]
        },
        {
          "heading": "Sei freundlich.",
          "paragraphs": [
            "Keine Verspottung anderer Menschen, keine nicht jugendfreien Inhalte, keine Hasssymbole. Wenn ein Fremder im Mittelpunkt deiner Aufnahme steht, stell dir vor, wie er sie sieht."
          ]
        },
        {
          "heading": "Minderjährige",
          "paragraphs": [
            "Stellt die Kinder nicht in den Mittelpunkt; sonst könnten wir den Blick verlieren."
          ]
        },
        {
          "heading": "Hat jemand auf deinem Foto etwas dagegen?",
          "paragraphs": [
            "Sie gewinnen. Immer."
          ]
        }
      ]
    }
  },
  "es": {
    "terms": {
      "title": "Condiciones de uso",
      "sections": [
        {
          "heading": "1. De qué se trata",
          "paragraphs": [
            "One Tribe es un proyecto de aficionados no oficial y sin ánimo de lucro: un archivo de recuerdos compartidos para la comunidad del hard-dance. No está afiliado, ni cuenta con el respaldo ni tiene relación alguna con Q-dance, Defqon.1 ni con ningún festival, artista o sello discográfico."
          ]
        },
        {
          "heading": "2. Tu contenido",
          "paragraphs": [
            "Al subir una foto o un GIF, o al enlazar un vídeo («Recuerdo»), confirmas que: lo has capturado tú mismo y tienes los derechos para compartirlo; fue tomado en un evento musical al que asististe; concedes a One Tribe una licencia no exclusiva, mundial y libre de derechos de autor para alojar, mostrar, redimensionar y traducir su pie de foto, con el único fin de gestionar este sitio web.",
            "La propiedad sigue siendo tuya. Puedes eliminar tu «Memory» en cualquier momento utilizando el enlace de eliminación."
          ]
        },
        {
          "heading": "3. Lo que no puedes subir",
          "paragraphs": [
            "Contenido que no hayas grabado tú mismo; grabaciones continuas de actuaciones que incluyan canciones completas («set rips»); material oficial (vídeos posteriores al concierto, fotos profesionales, capturas de retransmisiones); contenido no apto para el trabajo (NSFW) o de carácter sexual; contenido centrado en menores; imágenes generadas por IA o manipuladas que se presenten como momentos reales; spam o anuncios; contenido que se burle o menosprecie a personas identificables."
          ]
        },
        {
          "heading": "4. Moderación",
          "paragraphs": [
            "Las publicaciones aparecen en el muro de inmediato. Revisamos las publicaciones recientes y las denuncias tras su publicación, y podemos ocultar o eliminar cualquier contenido a nuestra discreción. Atendemos con rapidez las solicitudes de los titulares de derechos y las relacionadas con la privacidad (véase «retirada de contenidos»), y cada «Memory» cuenta con un enlace para denunciarlo."
          ]
        },
        {
          "heading": "5. Ausencia de garantía; limitación",
          "paragraphs": [
            "El sitio web se ofrece «tal cual», de forma gratuita. Las donaciones voluntarias solo cubren los gastos de alojamiento y no otorgan ningún beneficio, función ni prioridad. En la medida en que lo permita la ley, no aceptamos ninguna responsabilidad por los daños que puedan derivarse del uso del sitio web. El contenido refleja la opinión de quienes lo publican, no la del administrador."
          ]
        },
        {
          "heading": "6. Modificaciones; contacto",
          "paragraphs": [
            "Podemos actualizar estas condiciones; el uso continuado implica su aceptación. Contacto: privacy@onetribe.world."
          ]
        }
      ]
    },
    "privacy": {
      "title": "Política de privacidad",
      "sections": [
        {
          "heading": "1. Quiénes somos",
          "paragraphs": [
            "One Tribe (onetribe.world) es un proyecto de aficionados sin ánimo de lucro gestionado desde Corea del Sur. Contacto: privacy@onetribe.world."
          ]
        },
        {
          "heading": "2. Qué datos recopilamos",
          "paragraphs": [
            "Recuerdos: fotos o GIF que subas y enlaces a vídeos que incrustes, pies de foto, evento, ciudad y año, un nombre de usuario opcional y un enlace a redes sociales. Se publican de forma pública de inmediato; pueden ocultarse o eliminarse tras una revisión o una denuncia.",
            "Cuenta (opcional): ID de cuenta (anónima por defecto), nombre de usuario, país de origen, registro de asistencia a festivales («Passport») y —solo si decides vincularlos— tu dirección de correo electrónico o tu cuenta de Google.",
            "Aspectos técnicos: análisis respetuosos con la privacidad (sin seguimiento entre sitios web, sin cookies publicitarias) y los registros necesarios para el funcionamiento del servicio.",
            "No utilizamos el reconocimiento facial ni el etiquetado automático de personas. No vendemos datos."
          ]
        },
        {
          "heading": "3. Personas en fotos de multitudes",
          "paragraphs": [
            "Es posible que en las fotos del festival aparezcan otros asistentes. Nuestra base jurídica para su publicación es el interés legítimo en la documentación comunitaria de eventos públicos, sopesado con tus derechos.",
            "Si sales en una foto y quieres que la eliminemos o la difuminemos, avísanos: actuaremos en un plazo de 48 horas, sin hacerte preguntas: privacy@onetribe.world."
          ]
        },
        {
          "heading": "4. Tus derechos (RGPD)",
          "paragraphs": [
            "Acceso, rectificación, supresión, limitación del tratamiento, oposición, portabilidad. Puedes eliminar tú mismo tu pasaporte en la página del pasaporte; tus momentos permanecerán en el muro, de forma anónima, y cada uno de ellos contará con su propio enlace de eliminación. Envía un correo electrónico a privacy@onetribe.world para cualquier otra cuestión. También puedes presentar una reclamación ante tu autoridad local de protección de datos."
          ]
        },
        {
          "heading": "5. Almacenamiento y procesadores",
          "paragraphs": [
            "El contenido se almacena en los servidores de nuestros proveedores de infraestructura (base de datos/autenticación: Supabase; archivos multimedia: Cloudflare R2; traducción: DeepL; correos electrónicos de inicio de sesión: Resend). Los subtítulos se traducen automáticamente; el texto traducido se almacena en caché. Los datos pueden tratarse en la UE y en EE. UU. bajo las garantías habituales.",
            "Las donaciones las gestionan externamente Ko-fi y GitHub Sponsors; nosotros no recibimos ningún dato relativo a los pagos."
          ]
        },
        {
          "heading": "6. Retención",
          "paragraphs": [
            "Los «Recuerdos» publicados permanecen almacenados hasta que los elimines o hasta que una solicitud válida los elimine. El contenido eliminado se borra de los sistemas activos en un plazo de 30 días."
          ]
        },
        {
          "heading": "7. Menores de edad",
          "paragraphs": [
            "Esta página web no está dirigida a niños. Si se nos solicita o a nuestra discreción, difuminamos o eliminamos las imágenes en las que aparecen menores."
          ]
        }
      ]
    },
    "takedown": {
      "title": "Derechos de autor y eliminación",
      "sections": [
        {
          "paragraphs": [
            "Solicitudes de eliminación: lo hacemos sencillo."
          ]
        },
        {
          "heading": "¿Lo has subido y quieres borrarlo?",
          "paragraphs": [
            "Utiliza el enlace de eliminación que has recibido o envíanos un correo electrónico; lo eliminaremos de inmediato."
          ]
        },
        {
          "heading": "¿Sales en una foto y no quieres salir?",
          "paragraphs": [
            "Envía un correo electrónico a privacy@onetribe.world con el enlace a la foto. Se eliminará o se difuminará en un plazo de 48 horas, sin hacer preguntas."
          ]
        },
        {
          "heading": "Eres titular de derechos",
          "paragraphs": [
            "(artista, discográfica, festival, fotógrafo): envía un correo electrónico a privacy@onetribe.world indicando (1) el enlace al contenido, (2) qué derechos tienes sobre él y (3) tus datos de contacto. Revisamos las reclamaciones con rapidez y eliminamos aquellas que sean válidas, normalmente en un plazo de 24 a 48 horas. A quienes reincidan en las infracciones se les bloqueará la posibilidad de subir contenido.",
            "Contra-notificación: si se ha eliminado tu contenido y crees que se trata de un error, responde explicando el motivo; es posible que lo restablezcamos tras revisarlo.",
            "Somos seguidores, no adversarios. Si hay algo que te molesta, dínoslo y lo retiraremos."
          ]
        }
      ]
    },
    "guidelines": {
      "title": "Normas de la comunidad",
      "sections": [
        {
          "heading": "Que sea tuyo.",
          "paragraphs": [
            "Sube únicamente lo que hayas grabado tú mismo."
          ]
        },
        {
          "heading": "Sé auténtico.",
          "paragraphs": [
            "Solo momentos reales: nada de imágenes generadas por IA ni capturas de medios oficiales."
          ]
        },
        {
          "heading": "Sé breve.",
          "paragraphs": [
            "Fotos y GIF: enlaza un vídeo en lugar de subirlo. No publiques grabaciones completas: apoya a los artistas."
          ]
        },
        {
          "heading": "Sé amable.",
          "paragraphs": [
            "No se permite burlarse de nadie, ni contenido no apto para el trabajo, ni símbolos de odio. Si un desconocido es el protagonista de tu foto, imagina que él la viera."
          ]
        },
        {
          "heading": "Menores de edad",
          "paragraphs": [
            "No pongáis a los niños en el centro de atención; podríamos perder la perspectiva."
          ]
        },
        {
          "heading": "¿Hay alguien en tu foto que se oponga?",
          "paragraphs": [
            "Ellos ganan. Siempre."
          ]
        }
      ]
    }
  },
  "fr": {
    "terms": {
      "title": "Conditions générales d'utilisation",
      "sections": [
        {
          "heading": "1. De quoi s'agit-il ?",
          "paragraphs": [
            "One Tribe est un projet de fans non officiel et à but non lucratif — une archive de souvenirs partagés destinée à la communauté de la « hard-dance ». Il n'est ni affilié à, ni soutenu par, ni lié à Q-dance, Defqon.1, ni à aucun festival, artiste ou label."
          ]
        },
        {
          "heading": "2. Votre contenu",
          "paragraphs": [
            "Lorsque vous publiez une photo ou un GIF, ou que vous ajoutez un lien vers une vidéo (« Souvenir »), vous confirmez que : vous en êtes l'auteur et que vous détenez les droits nécessaires pour la partager ; elle a été prise lors d'un événement musical auquel vous avez assisté ; vous accordez à One Tribe une licence non exclusive, mondiale et libre de droits pour héberger, afficher, redimensionner et traduire sa légende, dans le seul but d’exploiter ce site.",
            "Vous en restez propriétaire. Vous pouvez supprimer votre « Memory » à tout moment à l'aide de votre lien de suppression."
          ]
        },
        {
          "heading": "3. Ce que vous n'avez pas le droit de mettre en ligne",
          "paragraphs": [
            "Contenu que vous n'avez pas enregistré vous-même ; enregistrements complets et ininterrompus de concerts (« set rips ») ; médias officiels (vidéos de fin de concert, photos professionnelles, captures d'émissions) ; contenu NSFW ou à caractère sexuel ; contenu mettant en scène des mineurs ; images générées par IA ou retouchées présentées comme des moments réels ; spam ou publicités ; contenu se moquant de personnes identifiables ou les rabaissant."
          ]
        },
        {
          "heading": "4. Modération",
          "paragraphs": [
            "Les publications apparaissent immédiatement sur le mur. Nous examinons les publications récentes et les signalements après leur mise en ligne, et nous nous réservons le droit de masquer ou de supprimer tout contenu à notre entière discrétion. Nous traitons rapidement les demandes des ayants droit et celles relatives à la vie privée (voir « retrait »), et chaque « Memory » comporte un lien permettant de le signaler."
          ]
        },
        {
          "heading": "5. Absence de garantie ; limitation de responsabilité",
          "paragraphs": [
            "Le site est mis à disposition « tel quel », gratuitement. Les dons volontaires servent uniquement à couvrir les frais d'hébergement et ne confèrent aucun avantage, aucune fonctionnalité ni aucune priorité. Dans les limites autorisées par la loi, nous déclinons toute responsabilité pour les dommages résultant de l'utilisation du site. Le contenu reflète les opinions de ses auteurs et non celles de l'exploitant."
          ]
        },
        {
          "heading": "6. Modifications ; contact",
          "paragraphs": [
            "Nous nous réservons le droit de mettre à jour les présentes conditions ; en continuant à utiliser ce site, vous acceptez ces modifications. Contact : privacy@onetribe.world."
          ]
        }
      ]
    },
    "privacy": {
      "title": "Politique de confidentialité",
      "sections": [
        {
          "heading": "1. Qui sommes-nous ?",
          "paragraphs": [
            "One Tribe (onetribe.world) est un projet de fans à but non commercial géré depuis la Corée du Sud. Contact : privacy@onetribe.world."
          ]
        },
        {
          "heading": "2. Les données que nous collectons",
          "paragraphs": [
            "Souvenirs : photos/GIF que vous publiez et liens vers des vidéos que vous intégrez, légendes, événement/ville/année, nom d'affichage facultatif et lien vers les réseaux sociaux. Publiés immédiatement ; peuvent être masqués ou supprimés à la suite d'un examen ou d'un signalement.",
            "Compte (facultatif) : identifiant du compte (anonyme par défaut), nom d'affichage, pays d'origine, historique de participation aux festivals (« Passport ») et — uniquement si vous choisissez de les associer — votre adresse e-mail ou votre identifiant Google.",
            "Aspects techniques : outils d'analyse respectueux de la vie privée (pas de suivi intersite, pas de cookies publicitaires) et fichiers journaux nécessaires au fonctionnement du service.",
            "Nous n'utilisons ni la reconnaissance faciale ni le marquage automatique des personnes. Nous ne vendons pas de données."
          ]
        },
        {
          "heading": "3. Les personnes sur les photos de foule",
          "paragraphs": [
            "Les photos prises lors du festival peuvent montrer d'autres participants. Notre base juridique pour leur publication est l'intérêt légitime à documenter, au nom de la communauté, des événements publics, dans le respect de vos droits.",
            "Si vous figurez sur une photo et que vous souhaitez qu'elle soit supprimée ou floutée, faites-le-nous savoir : nous interviendrons dans les 48 heures, sans poser de questions : privacy@onetribe.world."
          ]
        },
        {
          "heading": "4. Vos droits (RGPD)",
          "paragraphs": [
            "Accès, rectification, effacement, limitation du traitement, opposition, portabilité. Vous pouvez supprimer vous-même votre « passeport » sur la page dédiée — vos moments restent affichés sur le mur, anonymisés, chacun accompagné de son propre lien de suppression. Envoyez un e-mail à privacy@onetribe.world pour toute autre question. Vous pouvez également déposer une réclamation auprès de l'autorité locale chargée de la protection des données."
          ]
        },
        {
          "heading": "5. Stockage et processeurs",
          "paragraphs": [
            "Le contenu est hébergé chez nos fournisseurs d'infrastructure (base de données/authentification : Supabase ; médias : Cloudflare R2 ; traduction : DeepL ; e-mails de connexion : Resend). Les légendes sont traduites automatiquement ; le texte traduit est mis en cache. Les données peuvent être traitées dans l'UE et aux États-Unis dans le respect des garanties standard.",
            "Les dons sont traités en externe par Ko-fi et GitHub Sponsors ; nous ne recevons aucune donnée relative aux paiements."
          ]
        },
        {
          "heading": "6. Fidélisation",
          "paragraphs": [
            "Les « Memories » publiés restent en ligne jusqu'à ce que vous les supprimiez ou qu'une demande valide entraîne leur suppression. Le contenu supprimé est effacé des systèmes actifs dans un délai de 30 jours."
          ]
        },
        {
          "heading": "7. Mineurs",
          "paragraphs": [
            "Ce site ne s'adresse pas aux enfants. Sur demande ou à notre entière discrétion, nous floutons ou supprimons les images mettant en scène des mineurs."
          ]
        }
      ]
    },
    "takedown": {
      "title": "Droits d'auteur et retrait",
      "sections": [
        {
          "paragraphs": [
            "Demandes de suppression — nous faisons en sorte que ce soit simple."
          ]
        },
        {
          "heading": "Vous l'avez mis en ligne et vous voulez le supprimer ?",
          "paragraphs": [
            "Utilisez le lien de suppression que vous avez reçu ou envoyez-nous un e-mail : votre compte sera supprimé immédiatement."
          ]
        },
        {
          "heading": "Vous figurez sur une photo et vous ne souhaitez pas y apparaître ?",
          "paragraphs": [
            "Envoyez un e-mail à privacy@onetribe.world en indiquant le lien vers la photo. Elle sera supprimée ou floutée dans les 48 heures, sans aucune question."
          ]
        },
        {
          "heading": "Vous êtes titulaire de droits",
          "paragraphs": [
            "(artiste, label, festival, photographe) : envoyez un e-mail à privacy@onetribe.world en précisant (1) le lien vers le contenu, (2) les droits que vous détenez, (3) vos coordonnées. Nous examinons rapidement les demandes et supprimons les contenus faisant l'objet de réclamations valables, généralement dans un délai de 24 à 48 heures. Les contrevenants récidivistes se verront interdire tout téléchargement.",
            "Contre-notification : si votre contenu a été supprimé et que vous estimez qu'il s'agit d'une erreur, répondez en fournissant une explication ; nous pourrons le rétablir après examen.",
            "Nous sommes des fans, pas des adversaires. Si quelque chose vous dérange, dites-le-nous et on le retirera."
          ]
        }
      ]
    },
    "guidelines": {
      "title": "Règles de la communauté",
      "sections": [
        {
          "heading": "Garde-le pour toi.",
          "paragraphs": [
            "Ne publiez que les photos que vous avez prises vous-même."
          ]
        },
        {
          "heading": "Restez vous-même.",
          "paragraphs": [
            "Uniquement des moments réels — pas d'images générées par IA, pas d'extraits tirés des médias officiels."
          ]
        },
        {
          "heading": "Soyez concis.",
          "paragraphs": [
            "Photos et GIF — ajoutez un lien vers une vidéo plutôt que de la mettre en ligne. Pas d'enregistrements complets — soutenez les artistes."
          ]
        },
        {
          "heading": "Restez aimable.",
          "paragraphs": [
            "Pas de moqueries, pas de contenu inapproprié au travail, pas de symboles haineux. Si un inconnu est le sujet de votre photo, imaginez-le en train de la voir."
          ]
        },
        {
          "heading": "Mineurs",
          "paragraphs": [
            "Ne mettez pas les enfants au centre de l'attention ; on risque de perdre de vue l'essentiel."
          ]
        },
        {
          "heading": "Y a-t-il quelqu'un sur votre photo qui s'y oppose ?",
          "paragraphs": [
            "Ce sont eux qui gagnent. Toujours."
          ]
        }
      ]
    }
  },
  "it": {
    "terms": {
      "title": "Condizioni di servizio",
      "sections": [
        {
          "heading": "1. Di cosa si tratta",
          "paragraphs": [
            "One Tribe è un progetto amatoriale non ufficiale e non commerciale: un archivio di ricordi condivisi dedicato alla comunità dell’hard-dance. Non è affiliato, né avallato, né collegato a Q-dance, Defqon.1 o a qualsiasi altro festival, artista o etichetta discografica."
          ]
        },
        {
          "heading": "2. I tuoi contenuti",
          "paragraphs": [
            "Quando carichi una foto o una GIF, oppure inserisci il link a un video (“Ricordo”), confermi che: l’hai scattata o registrata tu stesso e ne detieni i diritti di condivisione; è stata scattata o registrata durante un evento musicale a cui hai partecipato; concedi a One Tribe una licenza non esclusiva, valida in tutto il mondo e esente da royalty per ospitare, visualizzare, ridimensionare e tradurre la didascalia, esclusivamente ai fini del funzionamento di questo sito.",
            "La proprietà rimane a te. Puoi cancellare la tua Memory in qualsiasi momento utilizzando il link di cancellazione."
          ]
        },
        {
          "heading": "3. Cosa non è consentito caricare",
          "paragraphs": [
            "Contenuti non registrati dall’utente; registrazioni continue di intere esibizioni (“set rips”); contenuti multimediali ufficiali (aftermovie, foto professionali, registrazioni di trasmissioni televisive); contenuti NSFW o a carattere sessuale; contenuti incentrati su minori; immagini generate dall’intelligenza artificiale o manipolate presentate come momenti reali; spam o pubblicità; contenuti che deridono o sminuiscono persone identificabili."
          ]
        },
        {
          "heading": "4. Moderazione",
          "paragraphs": [
            "I contenuti caricati vengono visualizzati immediatamente sulla bacheca. Esaminiamo i contenuti caricati di recente e le segnalazioni dopo la pubblicazione e ci riserviamo il diritto di nascondere o rimuovere qualsiasi contenuto a nostra discrezione. Rispondiamo tempestivamente alle richieste dei titolari dei diritti e in materia di privacy (vedi “rimozione dei contenuti”), e ogni Memory dispone di un link per la segnalazione."
          ]
        },
        {
          "heading": "5. Assenza di garanzia; limitazione",
          "paragraphs": [
            "Il sito viene fornito \"così com'è\", a titolo gratuito. Le donazioni volontarie coprono esclusivamente i costi di hosting e non conferiscono alcun vantaggio, funzionalità o priorità. Nella misura massima consentita dalla legge, decliniamo ogni responsabilità per eventuali danni derivanti dall'utilizzo del sito. I contenuti riflettono il punto di vista di chi li ha caricati, non quello del gestore."
          ]
        },
        {
          "heading": "6. Modifiche; contatti",
          "paragraphs": [
            "Ci riserviamo il diritto di aggiornare i presenti termini; l'uso continuato implica l'accettazione. Contatti: privacy@onetribe.world."
          ]
        }
      ]
    },
    "privacy": {
      "title": "Informativa sulla privacy",
      "sections": [
        {
          "heading": "1. Chi siamo",
          "paragraphs": [
            "One Tribe (onetribe.world) è un progetto amatoriale senza scopo di lucro gestito dalla Corea del Sud. Contatti: privacy@onetribe.world."
          ]
        },
        {
          "heading": "2. Quali dati raccogliamo",
          "paragraphs": [
            "Ricordi: foto/GIF caricate e link a video incorporati, didascalie, evento/città/anno, un nome visualizzato facoltativo e un link ai social. Pubblicati immediatamente in modo pubblico; possono essere nascosti o rimossi a seguito di revisione o segnalazione.",
            "Account (facoltativo): ID account (anonimo per impostazione predefinita), nome visualizzato, paese di residenza, registro delle partecipazioni ai festival (“Passport”) e — solo se si sceglie di collegarli — l’indirizzo e-mail o l’identificativo dell’account Google.",
            "Aspetti tecnici: analisi dei dati nel rispetto della privacy (nessun tracciamento tra siti, nessun cookie pubblicitario) e log necessari per il funzionamento del servizio.",
            "Non utilizziamo sistemi di riconoscimento facciale né di tagging automatico delle persone. Non vendiamo dati."
          ]
        },
        {
          "heading": "3. Persone nelle foto di folla",
          "paragraphs": [
            "Le foto del festival potrebbero ritrarre altri partecipanti. La nostra base giuridica per la pubblicazione è costituita dal legittimo interesse alla documentazione comunitaria di eventi pubblici, bilanciato rispetto ai tuoi diritti.",
            "Se compari in una foto e desideri che venga rimossa o sfocata, comunicacelo: provvederemo entro 48 ore, senza fare domande: privacy@onetribe.world."
          ]
        },
        {
          "heading": "4. I tuoi diritti (GDPR)",
          "paragraphs": [
            "Accesso, rettifica, cancellazione, limitazione del trattamento, opposizione, portabilità. Puoi cancellare tu stesso il tuo passaporto dalla pagina dedicata: i tuoi momenti rimarranno sulla bacheca, in forma anonima, ciascuno con il proprio link di cancellazione. Per qualsiasi altra richiesta, invia un’e-mail all’indirizzo privacy@onetribe.world. Puoi inoltre presentare un reclamo all’autorità locale garante della protezione dei dati."
          ]
        },
        {
          "heading": "5. Archiviazione e elaboratori",
          "paragraphs": [
            "I contenuti sono archiviati presso i nostri fornitori di infrastrutture (database/autenticazione: Supabase; file multimediali: Cloudflare R2; traduzione: DeepL; e-mail di accesso: Resend). Le didascalie sono tradotte automaticamente; il testo tradotto viene memorizzato nella cache. I dati possono essere trattati nell'UE e negli Stati Uniti nel rispetto delle garanzie standard.",
            "Le donazioni vengono gestite esternamente da Ko-fi e GitHub Sponsors; non riceviamo alcun dato relativo ai pagamenti."
          ]
        },
        {
          "heading": "6. Fidelizzazione",
          "paragraphs": [
            "I \"Memories\" pubblicati rimangono visibili finché non li elimini o non vengono rimossi in seguito a una richiesta valida. I contenuti eliminati vengono cancellati definitivamente dai sistemi attivi entro 30 giorni."
          ]
        },
        {
          "heading": "7. Minori",
          "paragraphs": [
            "Il sito non è rivolto ai bambini. Su richiesta o a nostra discrezione, sfociamo o rimuoviamo le immagini che ritraggono minori."
          ]
        }
      ]
    },
    "takedown": {
      "title": "Diritti d'autore e rimozione",
      "sections": [
        {
          "paragraphs": [
            "Richieste di rimozione: cerchiamo di semplificare le cose."
          ]
        },
        {
          "heading": "L'hai caricato e ora vuoi eliminarlo?",
          "paragraphs": [
            "Utilizza il link di cancellazione che hai ricevuto oppure inviaci un’e-mail: provvederemo a rimuoverlo immediatamente."
          ]
        },
        {
          "heading": "Sei in una foto e non vorresti esserci?",
          "paragraphs": [
            "Invia un'e-mail a privacy@onetribe.world con il link alla foto. La foto verrà rimossa o sfocata entro 48 ore, senza alcuna domanda."
          ]
        },
        {
          "heading": "Sei un titolare dei diritti",
          "paragraphs": [
            "(artista, etichetta discografica, festival, fotografo): invia un'e-mail all'indirizzo privacy@onetribe.world indicando (1) il link al contenuto, (2) i tuoi diritti di proprietà, (3) i tuoi recapiti. Esamineremo tempestivamente la segnalazione e provvederemo a rimuovere i contenuti oggetto di reclami fondati, solitamente entro 24-48 ore. A chi commette violazioni ripetute verrà impedito di caricare contenuti.",
            "Contronotifica: se il tuo contenuto è stato rimosso e ritieni che si tratti di un errore, rispondi fornendo una spiegazione; potremmo ripristinarlo dopo averlo esaminato.",
            "Siamo fan, non avversari. Se qualcosa ti dà fastidio, diccelo e lo toglieremo."
          ]
        }
      ]
    },
    "guidelines": {
      "title": "Linee guida della community",
      "sections": [
        {
          "heading": "Tienitelo per te.",
          "paragraphs": [
            "Carica solo ciò che hai scattato tu stesso."
          ]
        },
        {
          "heading": "Sii te stesso.",
          "paragraphs": [
            "Solo immagini reali — niente immagini generate dall'intelligenza artificiale, niente immagini tratte dai media ufficiali."
          ]
        },
        {
          "heading": "Sii conciso.",
          "paragraphs": [
            "Foto e GIF: inserite il link a un video invece di caricarlo. Niente registrazioni complete: sostenete gli artisti."
          ]
        },
        {
          "heading": "Sii gentile.",
          "paragraphs": [
            "Niente prese in giro, niente contenuti non adatti al lavoro, niente simboli di odio. Se il soggetto della tua foto è uno sconosciuto, immagina come si sentirebbe vedendola."
          ]
        },
        {
          "heading": "Minori",
          "paragraphs": [
            "Non mettete i bambini al centro dell’attenzione; potremmo perdere di vista il quadro generale."
          ]
        },
        {
          "heading": "C'è qualcuno nella tua foto che si oppone?",
          "paragraphs": [
            "Vincono. Sempre."
          ]
        }
      ]
    }
  },
  "pt": {
    "terms": {
      "title": "Termos de Serviço",
      "sections": [
        {
          "heading": "1. O que é isto",
          "paragraphs": [
            "O One Tribe é um projeto não oficial e não comercial criado por fãs — um arquivo de memórias partilhadas para a comunidade do hard-dance. Não está afiliado, nem é apoiado ou associado à Q-dance, à Defqon.1, nem a qualquer festival, artista ou editora."
          ]
        },
        {
          "heading": "2. O seu conteúdo",
          "paragraphs": [
            "Ao carregares uma fotografia ou um GIF, ou ao partilhares um vídeo («Memória»), confirmas que: foste tu próprio que o captaste e deténs os direitos para o partilhar; foi captado num evento musical em que estiveste presente; concede à One Tribe uma licença não exclusiva, mundial e isenta de direitos de autor para alojar, exibir, redimensionar e traduzir a sua legenda, exclusivamente para o funcionamento deste site.",
            "A propriedade continua a ser sua. Pode eliminar a sua Memória a qualquer momento através do seu link de eliminação."
          ]
        },
        {
          "heading": "3. O que não pode carregar",
          "paragraphs": [
            "Conteúdo que não foi gravado por si; gravações contínuas de atuações com músicas completas («set rips»); meios de comunicação oficiais (vídeos pós-espetáculo, fotografias profissionais, capturas de transmissões); Conteúdo impróprio para o local de trabalho (NSFW) ou de caráter sexual; conteúdo centrado em menores; imagens geradas por IA ou manipuladas apresentadas como momentos reais; spam ou anúncios; conteúdo que ridicularize ou humilhe pessoas identificáveis."
          ]
        },
        {
          "heading": "4. Moderação",
          "paragraphs": [
            "As publicações aparecem imediatamente no mural. Analisamos as publicações recentes e as denúncias após a publicação, podendo ocultar ou remover qualquer conteúdo, a nosso critério. Atendemos rapidamente aos pedidos dos titulares de direitos e às solicitações de privacidade (ver remoção), e cada Memória tem um link para denunciar."
          ]
        },
        {
          "heading": "5. Ausência de garantia; limitação",
          "paragraphs": [
            "O site é disponibilizado «tal como está», a título gratuito. As doações voluntárias destinam-se exclusivamente a cobrir os custos de alojamento e não conferem quaisquer benefícios, funcionalidades ou prioridade. Na medida do permitido por lei, não assumimos qualquer responsabilidade por danos decorrentes da utilização do site. O conteúdo reflete a opinião dos seus autores, e não a do operador."
          ]
        },
        {
          "heading": "6. Alterações; contacto",
          "paragraphs": [
            "Podemos atualizar estes termos; a utilização continuada implica a aceitação dos mesmos. Contacto: privacy@onetribe.world."
          ]
        }
      ]
    },
    "privacy": {
      "title": "Política de Privacidade",
      "sections": [
        {
          "heading": "1. Quem somos",
          "paragraphs": [
            "O One Tribe (onetribe.world) é um projeto de fãs sem fins lucrativos gerido a partir da Coreia do Sul. Contacto: privacy@onetribe.world."
          ]
        },
        {
          "heading": "2. O que recolhemos",
          "paragraphs": [
            "Memórias: fotografias/GIFs que carregas e links de vídeo que incorporas, legendas, evento/cidade/ano, um nome de exibição opcional e um link para redes sociais. Publicadas publicamente de imediato; podem ser ocultadas ou removidas após revisão ou denúncia.",
            "Conta (opcional): ID da conta (anónima por predefinição), nome de exibição, país de origem, registo de participação em festivais («Passaporte») e — apenas se optar por as associar — o seu endereço de e-mail ou a identidade da sua conta Google.",
            "Aspectos técnicos: análise de dados que respeita a privacidade (sem rastreamento entre sites, sem cookies publicitários) e registos necessários para o funcionamento do serviço.",
            "Não utilizamos reconhecimento facial nem a identificação automática de pessoas. Não vendemos dados."
          ]
        },
        {
          "heading": "3. Pessoas em fotografias de multidões",
          "paragraphs": [
            "As fotografias do festival podem mostrar outros participantes. A nossa base jurídica para a publicação é o interesse legítimo na documentação comunitária de eventos públicos, ponderado em relação aos seus direitos.",
            "Se aparecer numa fotografia e quiser que esta seja removida ou desfocada, informe-nos — tomaremos medidas no prazo de 48 horas, sem fazer perguntas: privacy@onetribe.world."
          ]
        },
        {
          "heading": "4. Os seus direitos (RGPD)",
          "paragraphs": [
            "Acesso, retificação, apagamento, limitação, oposição, portabilidade. Pode apagar o seu passaporte por conta própria na página do passaporte — os seus momentos permanecem no mural, anonimizados, cada um com o seu próprio link de apagamento. Envie um e-mail para privacy@onetribe.world para qualquer outra questão. Pode também apresentar uma reclamação junto da autoridade local de proteção de dados."
          ]
        },
        {
          "heading": "5. Armazenamento e processadores",
          "paragraphs": [
            "O conteúdo é armazenado junto dos nossos fornecedores de infraestrutura (base de dados/autenticação: Supabase; ficheiros multimédia: Cloudflare R2; tradução: DeepL; e-mails de início de sessão: Resend). As legendas são traduzidas automaticamente; o texto traduzido é armazenado em cache. Os dados podem ser tratados na UE e nos EUA ao abrigo de medidas de proteção padrão.",
            "As doações são processadas externamente pela Ko-fi e pelo GitHub Sponsors; não recebemos quaisquer dados relativos aos pagamentos."
          ]
        },
        {
          "heading": "6. Retenção",
          "paragraphs": [
            "As Memórias publicadas permanecem até que as elimine ou até que uma solicitação válida as remova. O conteúdo eliminado é apagado dos sistemas ativos no prazo de 30 dias."
          ]
        },
        {
          "heading": "7. Menores de idade",
          "paragraphs": [
            "O site não se destina a crianças. A pedido ou a nosso critério, desfocamos ou removemos imagens em que apareçam menores."
          ]
        }
      ]
    },
    "takedown": {
      "title": "Direitos de autor e remoção",
      "sections": [
        {
          "paragraphs": [
            "Pedidos de remoção — simplificamos este processo."
          ]
        },
        {
          "heading": "Carregaste o ficheiro e agora queres apagá-lo?",
          "paragraphs": [
            "Utilize o link de eliminação que recebeu ou envie-nos um e-mail — será eliminado imediatamente."
          ]
        },
        {
          "heading": "Estás numa fotografia e não queres aparecer nela?",
          "paragraphs": [
            "Envie um e-mail para privacy@onetribe.world com o link da fotografia. A imagem será removida ou desfocada no prazo de 48 horas, sem perguntas."
          ]
        },
        {
          "heading": "És titular de direitos",
          "paragraphs": [
            "(artista, editora, festival, fotógrafo): envie um e-mail para privacy@onetribe.world indicando (1) o link do conteúdo, (2) o que é da sua propriedade, (3) os seus dados de contacto. Analisamos rapidamente e removemos as reclamações válidas — normalmente no prazo de 24 a 48 horas. Os infratores reincidentes são impedidos de fazer uploads.",
            "Contra-notificação: se o seu conteúdo foi removido e considera que se tratou de um erro, responda com uma explicação; poderemos restaurá-lo após análise.",
            "Somos fãs, não adversários. Se algo te incomodar, diz-nos e nós retiramos."
          ]
        }
      ]
    },
    "guidelines": {
      "title": "Diretrizes da Comunidade",
      "sections": [
        {
          "heading": "Guarda isso para ti.",
          "paragraphs": [
            "Só deves publicar o que tenhas captado tu próprio."
          ]
        },
        {
          "heading": "Sê autêntico.",
          "paragraphs": [
            "Apenas momentos reais — sem imagens geradas por IA, sem imagens extraídas de meios de comunicação oficiais."
          ]
        },
        {
          "heading": "Seja breve.",
          "paragraphs": [
            "Fotografias e GIFs — partilhe um link para um vídeo em vez de o carregar. Não publique gravações completas de concertos — apoie os artistas."
          ]
        },
        {
          "heading": "Sê gentil.",
          "paragraphs": [
            "Não se pode gozar com as pessoas, não se pode publicar conteúdo impróprio para o local de trabalho, nem símbolos de ódio. Se um desconhecido for o protagonista da tua fotografia, imagina que ele a vai ver."
          ]
        },
        {
          "heading": "Menores de idade",
          "paragraphs": [
            "Não coloquem as crianças no centro das atenções; podemos perder o foco."
          ]
        },
        {
          "heading": "Alguém na tua foto tem alguma objeção?",
          "paragraphs": [
            "Eles ganham. Sempre."
          ]
        }
      ]
    }
  },
  "ja": {
    "terms": {
      "title": "利用規約",
      "sections": [
        {
          "heading": "1. これについて",
          "paragraphs": [
            "「One Tribe」は、非公式かつ非営利のファンプロジェクトであり、ハードダンス・コミュニティのための共有メモリアルアーカイブです。Q-dance、Defqon.1、その他のフェスティバル、アーティスト、レーベルとは一切関係がなく、それらの承認や提携も受けていません。"
          ]
        },
        {
          "heading": "2. コンテンツについて",
          "paragraphs": [
            "写真やGIFをアップロードしたり、動画（「メモリー」）へのリンクを貼ったりする場合、以下の事項を確認したものとみなされます：そのコンテンツはご自身で撮影したものであり、共有する権利を有していること；そのコンテンツは、ご自身が参加した音楽イベントで撮影されたものであること； また、本サイトの運営のみを目的として、One Tribeに対し、そのコンテンツをホスト、表示、サイズ変更、およびキャプションの翻訳を行うための非独占的、全世界的、ロイヤリティフリーのライセンスを付与するものとします。",
            "所有権は引き続きお客様にあります。削除リンクを使用して、いつでもご自身の「Memory」を削除することができます。"
          ]
        },
        {
          "heading": "3. アップロードしてはいけないもの",
          "paragraphs": [
            "収録されていないコンテンツ；公演の楽曲全編にわたる連続録音（「セット・リップ」）；公式メディア（アフタームービー、プロの写真、放送のキャプチャ）； NSFWまたは性的なコンテンツ；未成年者に焦点を当てたコンテンツ；実際の瞬間として提示されたAI生成または加工された画像；スパムや広告；特定可能な人物を嘲笑したり侮辱したりするコンテンツ。"
          ]
        },
        {
          "heading": "4. モデレーション",
          "paragraphs": [
            "投稿されたコンテンツは、すぐにウォールに表示されます。当社は公開後の最新の投稿や通報内容を審査し、独自の判断でコンテンツを非表示または削除する場合があります。権利者やプライバシーに関する要請には迅速に対応しており（削除要請についてはこちらをご覧ください）、すべての「Memory」には通報用のリンクが用意されています。"
          ]
        },
        {
          "heading": "5. 保証の否認・責任の制限",
          "paragraphs": [
            "本サイトは「現状有姿」のまま、無料で提供されています。任意の寄付はホスティング費用のみに充てられ、それによる特典、機能、または優先的な扱いは一切ありません。法律で認められる最大限の範囲において、当サイトは本サイトの利用に起因する損害について一切の責任を負いません。掲載内容は投稿者によるものであり、運営者によるものではありません。"
          ]
        },
        {
          "heading": "6. 変更・お問い合わせ",
          "paragraphs": [
            "当社は本規約を随時更新する場合があります。引き続きご利用いただくことは、その変更内容に同意したものとみなされます。お問い合わせ先：privacy@onetribe.world。"
          ]
        }
      ]
    },
    "privacy": {
      "title": "プライバシーポリシー",
      "sections": [
        {
          "heading": "1. 私たちについて",
          "paragraphs": [
            "One Tribe (onetribe.world) は、韓国を拠点に運営されている非営利のファンプロジェクトです。お問い合わせ：privacy@onetribe.world。"
          ]
        },
        {
          "heading": "2. 収集する情報",
          "paragraphs": [
            "思い出：アップロードした写真やGIF、埋め込んだ動画リンク、キャプション、イベント・都市・年、任意の表示名およびソーシャルメディアへのリンク。公開されるとすぐに誰でも閲覧可能になりますが、審査や通報により非表示にされたり削除されたりする場合があります。",
            "アカウント（任意）：アカウントID（デフォルトでは匿名）、表示名、居住国、フェスティバル参加履歴（「パスポート」）、および（連携を選択した場合のみ）メールアドレスまたはGoogleアカウントのID。",
            "技術面：プライバシーに配慮した分析機能（クロスサイト追跡なし、広告用クッキーなし）、およびサービスの運営に必要なログ。",
            "当社では、顔認識や人物の自動タグ付けは行っていません。また、データの販売も行っていません。"
          ]
        },
        {
          "heading": "3. 群衆の写真に写っている人々",
          "paragraphs": [
            "フェスティバルの写真には、他の参加者が写っている場合があります。当社がこれらの写真を公開する法的根拠は、公共のイベントを記録するという正当な利益であり、これと皆様の権利とのバランスを考慮した上で行われています。",
            "写真にご自身が写っており、その写真の削除やぼかし処理をご希望の場合は、お知らせください。理由を問わず、48時間以内に対応いたします：privacy@onetribe.world。"
          ]
        },
        {
          "heading": "4. お客様の権利（GDPR）",
          "paragraphs": [
            "アクセス、訂正、削除、処理の制限、異議申立て、データポータビリティ。パスポートページからご自身でパスポートを削除することができます。投稿された「モーメント」は、匿名化された状態でウォールに残り、それぞれに削除用リンクが付いています。その他のお問い合わせは、privacy@onetribe.world までメールでお寄せください。また、お住まいの地域のデータ保護当局に苦情を申し立てることも可能です。"
          ]
        },
        {
          "heading": "5. ストレージおよびプロセッサ",
          "paragraphs": [
            "コンテンツは、当社のインフラプロバイダー（データベース／認証：Supabase、メディア：Cloudflare R2、翻訳：DeepL、ログイン用メール：Resend）に保存されています。キャプションは機械翻訳されており、翻訳されたテキストはキャッシュされます。データは、標準的な保護措置の下、EUおよび米国で処理される場合があります。",
            "寄付の処理は、Ko-fiおよびGitHub Sponsorsによって外部で行われており、当方では支払いデータを受け取ることはありません。"
          ]
        },
        {
          "heading": "6. 顧客維持",
          "paragraphs": [
            "公開された「Memories」は、ユーザーが削除するか、有効なリクエストによって削除されるまで残ります。削除されたコンテンツは、30日以内に稼働中のシステムから完全に削除されます。"
          ]
        },
        {
          "heading": "7. 未成年者",
          "paragraphs": [
            "当サイトは子どもを対象としたものではありません。未成年者が写っている画像については、ご要望に応じて、または当社の判断により、ぼかし処理を施すか削除いたします。"
          ]
        }
      ]
    },
    "takedown": {
      "title": "著作権および削除について",
      "sections": [
        {
          "paragraphs": [
            "削除依頼 — 手続きはシンプルにしています。"
          ]
        },
        {
          "heading": "アップロードしたのに、削除したいんですか？",
          "paragraphs": [
            "受け取った削除リンクをご利用いただくか、弊社までメールをお送りください。直ちに削除いたします。"
          ]
        },
        {
          "heading": "写真に写り込んでしまったけど、写りたくない？",
          "paragraphs": [
            "写真のリンクを privacy@onetribe.world までメールでお送りください。48時間以内に削除またはぼかし処理を行います。理由の説明は一切不要です。"
          ]
        },
        {
          "heading": "あなたは権利者です",
          "paragraphs": [
            "（アーティスト、レーベル、フェスティバル、写真家）：(1) コンテンツのリンク、(2) ご自身が権利を保有しているもの、(3) 連絡先を明記の上、privacy@onetribe.world までメールをお送りください。迅速に確認を行い、正当な申し立てについては通常24～48時間以内に削除いたします。繰り返し権利侵害を行うユーザーについては、アップロードをブロックいたします。",
            "異議申し立て：ご自身のアップロードしたコンテンツが削除され、それが誤りであると思われる場合は、その理由を説明して返信してください。確認の上、復元する場合があります。",
            "私たちはファンであり、敵ではありません。何か気になることがあれば、お知らせください。すぐに削除します。"
          ]
        }
      ]
    },
    "guidelines": {
      "title": "コミュニティガイドライン",
      "sections": [
        {
          "heading": "自分だけのものにしておいてください。",
          "paragraphs": [
            "自分で撮影した写真のみをアップロードしてください。"
          ]
        },
        {
          "heading": "ありのままの自分でいよう。",
          "paragraphs": [
            "すべてがリアルな瞬間のみ — AI生成画像や公式メディアからの転載は一切ありません。"
          ]
        },
        {
          "heading": "手短にまとめてください。",
          "paragraphs": [
            "写真やGIF — 動画をアップロードするのではなく、リンクを貼ってください。フルセットの録画はご遠慮ください — アーティストを応援しましょう。"
          ]
        },
        {
          "heading": "親切な言葉遣いを心がけましょう。",
          "paragraphs": [
            "他人を嘲笑する内容、NSFW、ヘイトシンボルは禁止です。見知らぬ人が写真の主役になっている場合は、その人がその写真を見た時のことを想像してください。"
          ]
        },
        {
          "heading": "未成年者",
          "paragraphs": [
            "子供たちを主役にしないでください。そうすると、私たちの存在がぼやけてしまうかもしれません。"
          ]
        },
        {
          "heading": "写真に写っている誰かが異議を唱えていますか？",
          "paragraphs": [
            "彼らは勝つ。いつもだ。"
          ]
        }
      ]
    }
  },
  "ko": {
    "terms": {
      "title": "이용약관",
      "sections": [
        {
          "heading": "1. 이것이 무엇인지",
          "paragraphs": [
            "One Tribe는 비공식적이고 비영리적인 팬 프로젝트로, 하드 댄스 커뮤니티를 위한 공유 추억 아카이브입니다. 본 프로젝트는 Q-dance, Defqon.1 또는 그 밖의 어떤 페스티벌, 아티스트, 레이블과도 제휴하거나, 후원받거나, 관련이 없습니다."
          ]
        },
        {
          "heading": "2. 귀하의 콘텐츠",
          "paragraphs": [
            "사진이나 GIF를 업로드하거나 동영상(“메모리”)을 링크할 때, 귀하는 다음 사항을 확인하는 것으로 간주됩니다: 해당 콘텐츠를 직접 촬영했으며 공유할 권리를 보유하고 있음; 해당 콘텐츠가 귀하가 참석한 음악 행사에서 촬영된 것임; 귀하는 본 사이트 운영을 목적으로만 One Tribe에 해당 콘텐츠를 호스팅, 표시, 크기 조정 및 캡션 번역할 수 있는 비독점적, 전 세계적, 로열티 없는 라이선스를 부여합니다.",
            "소유권은 귀하에게 있습니다. 삭제 링크를 통해 언제든지 귀하의 메모리를 삭제할 수 있습니다."
          ]
        },
        {
          "heading": "3. 업로드할 수 없는 내용",
          "paragraphs": [
            "촬영하지 않은 콘텐츠; 공연의 전체 곡 연속 녹화 영상(“세트 립”); 공식 미디어(애프터무비, 프로 사진, 방송 캡처); 성인용(NSFW) 또는 성적 요소가 포함된 콘텐츠; 미성년자를 중심으로 한 콘텐츠; 실제 순간인 것처럼 제시된 AI 생성 또는 조작된 이미지; 스팸 또는 광고; 신원이 확인 가능한 인물을 조롱하거나 비하하는 콘텐츠."
          ]
        },
        {
          "heading": "4. 검토",
          "paragraphs": [
            "업로드된 콘텐츠는 즉시 타임라인에 표시됩니다. 당사는 게시 후 최근 업로드된 콘텐츠와 신고 내용을 검토하며, 재량에 따라 해당 콘텐츠를 숨기거나 삭제할 수 있습니다. 당사는 권리자 및 개인정보 보호 관련 요청을 신속하게 처리하며(‘게시물 삭제’ 참조), 모든 ‘메모리’에는 신고 링크가 제공됩니다."
          ]
        },
        {
          "heading": "5. 보증의 부인; 책임의 제한",
          "paragraphs": [
            "본 사이트는 “있는 그대로” 무료로 제공됩니다. 자발적인 기부금은 호스팅 비용만을 충당하며, 어떠한 혜택, 기능 또는 우선권도 부여하지 않습니다. 법이 허용하는 최대 한도 내에서, 당사는 본 사이트 이용으로 인해 발생하는 손해에 대해 어떠한 책임도 지지 않습니다. 게시된 콘텐츠는 운영자가 아닌 게시자의 견해를 반영합니다."
          ]
        },
        {
          "heading": "6. 변경 사항; 문의",
          "paragraphs": [
            "당사는 본 약관을 수시로 개정할 수 있으며, 서비스를 계속 이용하는 것은 개정된 약관에 동의하는 것으로 간주됩니다. 문의: privacy@onetribe.world."
          ]
        }
      ]
    },
    "privacy": {
      "title": "개인정보 처리방침",
      "sections": [
        {
          "heading": "1. 저희 소개",
          "paragraphs": [
            "One Tribe (onetribe.world)는 한국에서 운영되는 비영리 팬 프로젝트입니다. 문의: privacy@onetribe.world."
          ]
        },
        {
          "heading": "2. 수집하는 정보",
          "paragraphs": [
            "추억: 사용자가 업로드한 사진/GIF, 삽입한 동영상 링크, 캡션, 이벤트/도시/연도, 선택 사항인 표시 이름 및 소셜 링크. 게시 즉시 공개되며, 검토 또는 신고를 통해 숨겨지거나 삭제될 수 있습니다.",
            "계정 (선택 사항): 계정 ID(기본적으로 익명), 표시 이름, 거주 국가, 축제 참가 기록(“Passport”), 그리고 — 연동을 선택한 경우에만 — 이메일 주소 또는 Google 계정 ID.",
            "기술적 사항: 개인정보 보호에 중점을 둔 분석 기능(크로스사이트 추적 및 광고 쿠키 없음)과 서비스 운영에 필요한 로그.",
            "당사는 얼굴 인식이나 사람에 대한 자동 태깅 기능을 운영하지 않습니다. 또한 데이터를 판매하지 않습니다."
          ]
        },
        {
          "heading": "3. 군중 사진 속의 사람들",
          "paragraphs": [
            "축제 사진에는 다른 참가자들이 찍힐 수 있습니다. 당사가 해당 사진을 게시하는 법적 근거는 공공 행사에 대한 커뮤니티 기록이라는 정당한 이익이며, 이는 귀하의 권리와 균형을 이루고 있습니다.",
            "사진에 본인이 찍혀 있는데 해당 사진을 삭제하거나 흐리게 처리해 주기를 원하시면 저희에게 알려주세요. 아무런 질문 없이 48시간 이내에 조치를 취해 드리겠습니다: privacy@onetribe.world."
          ]
        },
        {
          "heading": "4. 귀하의 권리 (GDPR)",
          "paragraphs": [
            "열람, 정정, 삭제, 처리 제한, 이의 제기, 데이터 이동권. 여권 페이지에서 직접 여권을 삭제할 수 있습니다. 여러분의 ‘순간’은 익명 처리된 상태로 벽에 남아 있으며, 각 순간마다 별도의 삭제 링크가 제공됩니다. 그 외 문의 사항이 있으시면 privacy@onetribe.world으로 이메일을 보내주십시오. 또한 관할 지역 데이터 보호 당국에 불만을 제기할 수도 있습니다."
          ]
        },
        {
          "heading": "5. 저장 장치 및 프로세서",
          "paragraphs": [
            "콘텐츠는 당사의 인프라 제공업체에 저장됩니다(데이터베이스/인증: Supabase; 미디어: Cloudflare R2; 번역: DeepL; 로그인 이메일: Resend). 자막은 기계 번역되며, 번역된 텍스트는 캐시에 저장됩니다. 데이터는 표준 보호 조치에 따라 EU 및 미국에서 처리될 수 있습니다.",
            "기부금은 Ko-fi와 GitHub Sponsors를 통해 외부에서 처리되며, 당사는 결제 정보를 전혀 수신하지 않습니다."
          ]
        },
        {
          "heading": "6. 유지",
          "paragraphs": [
            "게시된 메모리는 사용자가 삭제하거나 유효한 요청에 의해 제거될 때까지 유지됩니다. 삭제된 콘텐츠는 30일 이내에 운영 중인 시스템에서 완전히 제거됩니다."
          ]
        },
        {
          "heading": "7. 미성년자",
          "paragraphs": [
            "본 사이트는 아동을 대상으로 하지 않습니다. 요청이 있거나 당사의 재량에 따라 미성년자가 주된 대상인 이미지는 흐리게 처리하거나 삭제합니다."
          ]
        }
      ]
    },
    "takedown": {
      "title": "저작권 및 게시물 삭제",
      "sections": [
        {
          "paragraphs": [
            "삭제 요청 — 저희는 이 절차를 간단하게 처리합니다."
          ]
        },
        {
          "heading": "업로드해 놓고 이제 지우고 싶으신가요?",
          "paragraphs": [
            "수신하신 삭제 링크를 이용하시거나 이메일을 보내주시면 즉시 삭제해 드리겠습니다."
          ]
        },
        {
          "heading": "사진에 찍혔는데, 그 사진에 나오고 싶지 않으신가요?",
          "paragraphs": [
            "사진 링크를 privacy@onetribe.world으로 보내주세요. 48시간 이내에 아무런 질문 없이 삭제하거나 모자이크 처리해 드리겠습니다."
          ]
        },
        {
          "heading": "귀하는 저작권자입니다",
          "paragraphs": [
            "(아티스트, 레이블, 페스티벌, 사진작가): (1) 콘텐츠 링크, (2) 소유권 정보, (3) 연락처를 기재하여 privacy@onetribe.world으로 이메일을 보내주십시오. 당사는 신속히 검토하여 정당한 청구 사항이 확인될 경우 해당 콘텐츠를 삭제합니다. 일반적으로 24~48시간 이내에 처리됩니다. 반복적으로 저작권을 침해하는 사용자의 경우 업로드가 차단됩니다.",
            "반박 통지: 업로드한 콘텐츠가 삭제되었으나 이는 오류라고 생각되시면, 사유를 설명하여 회신해 주십시오. 검토 후 해당 콘텐츠를 복원해 드릴 수 있습니다.",
            "우리는 적대자가 아니라 팬입니다. 마음에 들지 않는 내용이 있다면 알려주시면 바로 삭제하겠습니다."
          ]
        }
      ]
    },
    "guidelines": {
      "title": "커뮤니티 가이드라인",
      "sections": [
        {
          "heading": "그건 당신만의 것으로 간직하세요.",
          "paragraphs": [
            "직접 촬영한 사진만 업로드해 주세요."
          ]
        },
        {
          "heading": "솔직하게 행동해.",
          "paragraphs": [
            "오직 실제 순간들만 — AI 생성 이미지나 공식 미디어 자료는 없습니다."
          ]
        },
        {
          "heading": "간결하게 하세요.",
          "paragraphs": [
            "사진 및 GIF — 동영상을 직접 업로드하지 말고 링크를 걸어주세요. 전체 공연 영상은 올리지 마세요 — 아티스트를 응원해 주세요."
          ]
        },
        {
          "heading": "친절하게 대하세요.",
          "paragraphs": [
            "타인을 조롱하는 내용, 성인용 콘텐츠, 혐오 상징은 금지됩니다. 낯선 사람이 사진의 주인공이라면, 그 사람이 그 사진을 보는 모습을 상상해 보세요."
          ]
        },
        {
          "heading": "미성년자",
          "paragraphs": [
            "아이들을 중심에 두지 마세요. 그렇지 않으면 우리가 흐릿해질 수도 있습니다."
          ]
        },
        {
          "heading": "사진 속 누군가가 이의를 제기하나요?",
          "paragraphs": [
            "그들은 이긴다. 언제나."
          ]
        }
      ]
    }
  }
}

export const ABOUT_I18N: Record<Locale, { title: string; paragraphs: string[] }> =
{
  "en": {
    "title": "about",
    "paragraphs": [
      "One Tribe is built by a fan from South Korea who flies to Defqon.1 every year — a Weekend Warrior with a long flight home.",
      "When the 2026 weekend was canceled, thousands of us were left holding memories with nowhere to put them. So this wall exists: a place where the harder-styles community keeps the moments we took home — permanent, visual, and in every language we speak.",
      "Principles: fan-owned, non-commercial, no ads, no merch. The moments belong to the people who lived them. If something here bothers you, tell us and it comes down — see the takedown page.",
      "Not affiliated with Q-dance or Defqon.1 in any way."
    ]
  },
  "nl": {
    "title": "over",
    "paragraphs": [
      "One Tribe is opgezet door een fan uit Zuid-Korea die elk jaar naar Defqon.1 vliegt — een ‘Weekend Warrior’ met een lange terugvlucht.",
      "Toen het weekend van 2026 werd afgelast, bleven duizenden van ons achter met herinneringen die we nergens kwijt konden. Daarom is deze muur er: een plek waar de hard-styles-gemeenschap de momenten bewaart die we mee naar huis hebben genomen — blijvend, visueel en in alle talen die we spreken.",
      "Uitgangspunten: eigendom van fans, niet-commercieel, geen advertenties, geen merchandise. De momenten zijn van de mensen die ze hebben meegemaakt. Als iets je hier stoort, laat het ons dan weten en het wordt verwijderd — zie de pagina over het verwijderen van inhoud.",
      "Heeft op geen enkele wijze banden met Q-dance of Defqon.1."
    ]
  },
  "de": {
    "title": "Über",
    "paragraphs": [
      "„One Tribe“ wurde von einem Fan aus Südkorea ins Leben gerufen, der jedes Jahr zur Defqon.1 fliegt – ein „Weekend Warrior“ mit einem langen Heimflug vor sich.",
      "Als das Wochenende 2026 abgesagt wurde, blieben Tausende von uns mit Erinnerungen zurück, für die es keinen Platz gab. Deshalb gibt es diese Wand: einen Ort, an dem die Hard-Styles-Community die Momente bewahrt, die wir mit nach Hause genommen haben – dauerhaft, visuell und in jeder Sprache, die wir sprechen.",
      "Grundsätze: Von Fans betrieben, nicht kommerziell, keine Werbung, kein Fan-Merchandise. Die Momente gehören den Menschen, die sie erlebt haben. Sollte dich etwas hier stören, teile es uns mit, und es wird entfernt – siehe die Seite zur Entfernung von Inhalten.",
      "Steht in keinerlei Verbindung zu Q-dance oder Defqon.1."
    ]
  },
  "es": {
    "title": "Acerca de",
    "paragraphs": [
      "One Tribe es una iniciativa creada por un fan de Corea del Sur que viaja cada año en avión al Defqon.1: un «guerrero de fin de semana» al que le espera un largo vuelo de vuelta a casa.",
      "Cuando se canceló el fin de semana de 2026, miles de nosotros nos quedamos con recuerdos que no sabíamos dónde guardar. Por eso existe este muro: un lugar donde la comunidad de los estilos más duros conserva los momentos que nos llevamos a casa —permanentes, visuales y en todos los idiomas que hablamos—.",
      "Principios: gestionado por aficionados, sin ánimo de lucro, sin anuncios, sin merchandising. Estos momentos pertenecen a quienes los vivieron. Si algo de lo que aparece aquí te molesta, avísanos y lo retiraremos; consulta la página de retirada de contenidos.",
      "No tiene ninguna relación con Q-dance ni con Defqon.1."
    ]
  },
  "fr": {
    "title": "À propos de",
    "paragraphs": [
      "One Tribe a été créé par un fan sud-coréen qui se rend chaque année à Defqon.1 en avion — un « Weekend Warrior » qui doit ensuite affronter un long vol de retour.",
      "Lorsque le week-end de 2026 a été annulé, nous étions des milliers à nous retrouver avec des souvenirs que nous ne savions pas où mettre. C'est pourquoi ce mur existe : un lieu où la communauté des styles « hard » conserve les moments que nous avons ramenés chez nous — de manière permanente, visuelle et dans toutes les langues que nous parlons.",
      "Principes : site géré par des fans, à but non commercial, sans publicité ni produits dérivés. Ces moments appartiennent à ceux qui les ont vécus. Si quelque chose ici vous dérange, signalez-le-nous et nous le retirerons — consultez la page dédiée au retrait de contenu.",
      "N'a aucun lien, d'aucune sorte, avec Q-dance ou Defqon.1."
    ]
  },
  "it": {
    "title": "Informazioni su",
    "paragraphs": [
      "One Tribe è stato creato da un fan della Corea del Sud che ogni anno prende l’aereo per andare al Defqon.1: un “Weekend Warrior” che deve affrontare un lungo volo di ritorno.",
      "Quando il weekend del 2026 è stato annullato, migliaia di noi sono rimasti con dei ricordi che non sapevamo dove riporre. Ecco perché esiste questo muro: un luogo in cui la comunità degli stili più intensi conserva i momenti che ci siamo portati a casa — in modo permanente, visivo e in tutte le lingue che parliamo.",
      "Principi: gestito dai fan, non commerciale, senza pubblicità né merchandising. Questi momenti appartengono a chi li ha vissuti. Se qualcosa qui ti infastidisce, segnalacelo e verrà rimosso — consulta la pagina dedicata alla rimozione dei contenuti.",
      "Non è in alcun modo affiliato a Q-dance o Defqon.1."
    ]
  },
  "pt": {
    "title": "sobre",
    "paragraphs": [
      "O One Tribe foi criado por um fã da Coreia do Sul que viaja de avião para o Defqon.1 todos os anos — um «Weekend Warrior» com um longo voo de regresso a casa.",
      "Quando o fim de semana de 2026 foi cancelado, milhares de nós ficámos com memórias que não sabíamos onde guardar. É por isso que esta parede existe: um lugar onde a comunidade dos estilos mais intensos guarda os momentos que levámos para casa — de forma permanente, visual e em todas as línguas que falamos.",
      "Princípios: propriedade dos fãs, não comercial, sem anúncios, sem produtos promocionais. Os momentos pertencem às pessoas que os viveram. Se algo aqui te incomodar, avisa-nos e será removido — consulta a página de remoção.",
      "Não está de forma alguma associado à Q-dance nem à Defqon.1."
    ]
  },
  "ja": {
    "title": "概要",
    "paragraphs": [
      "「One Tribe」は、毎年Defqon.1に参加するために飛行機で韓国から駆けつけるファンによって運営されています。彼は、長い帰路を乗り越える「ウィークエンド・ウォリアー」なのです。",
      "2026年の週末イベントが中止になったとき、私たち何千人もの人々は、どこにも置き場のない思い出を抱えたまま取り残されてしまいました。そこでこの壁が生まれたのです。ハードスタイル・コミュニティが、持ち帰った瞬間を、永続的かつ視覚的に、そして私たちが話すあらゆる言語で残す場所として。",
      "基本方針：ファン所有、非営利、広告なし、グッズ販売なし。ここに掲載されている瞬間は、それを体験した人々自身のものです。もしここに掲載されている内容に不快感を覚えるものがあれば、お知らせください。該当するコンテンツは削除いたします。削除に関するページをご覧ください。",
      "Q-dance および Defqon.1 とは一切関係がありません。"
    ]
  },
  "ko": {
    "title": "소개",
    "paragraphs": [
      "‘One Tribe’는 매년 Defqon.1에 비행기를 타고 찾아가는 한국의 한 팬이 만든 프로젝트로, 귀국길에 긴 비행 시간을 견뎌야 하는 ‘주말 전사’입니다.",
      "2026년 주말 행사가 취소되었을 때, 우리 수천 명은 어디에도 담을 곳 없는 추억만 안고 남게 되었습니다. 그래서 이 벽이 존재합니다. 하드스타일 커뮤니티가 집으로 가져온 순간들을 영구적이고 시각적인 형태로, 우리가 사용하는 모든 언어로 간직하는 공간입니다.",
      "원칙: 팬 소유, 비영리, 광고 없음, 굿즈 없음. 이 순간들은 그 순간을 직접 경험한 사람들에게 속합니다. 이곳의 콘텐츠 중 불편한 점이 있다면 알려주시면 해당 콘텐츠를 삭제하겠습니다 — 삭제 요청 페이지를 참고해 주세요.",
      "Q-dance 또는 Defqon.1과는 어떠한 관련도 없습니다."
    ]
  }
}
