/**
 * Generate machine translations of the policy + about copy into every locale,
 * for the multilingual "all languages stacked" policy pages (docs/00 D18).
 *
 * English is the BINDING original; the non-EN entries are DeepL machine
 * translations, reviewed once by hand and committed. This is a build-time
 * generator, not a runtime path — legal text should be reviewed and versioned,
 * never translated live. Regenerate after editing policy-content.ts:
 *
 *   set -a; source .env.local; set +a; npx tsx scripts/translate-policies.ts
 *
 * (Uses DEEPL_API_KEY. Small volume — well within the Free 1M-char/month tier.)
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { POLICIES, ABOUT, type PolicyDoc } from '../src/lib/policy-content'
import { LOCALES, DEFAULT_LOCALE } from '../src/lib/locales'
import { createDeeplProvider } from '../src/lib/translate/deepl'

interface LocalizedDoc {
  title: string
  sections: { heading?: string; paragraphs: string[] }[]
}

const key = process.env.DEEPL_API_KEY
if (!key) throw new Error('DEEPL_API_KEY missing — run: set -a; source .env.local; set +a')

const deepl = createDeeplProvider(key)
const targets = LOCALES.filter((l) => l !== DEFAULT_LOCALE)
const slugs = Object.keys(POLICIES) as PolicyDoc['slug'][]

// `--only-missing`: keep already-translated locales verbatim and only DeepL the
// ones missing (or structurally stale) in the committed file. Use this when
// ADDING a locale, so the existing reviewed translations aren't re-machined
// (and the Free quota isn't spent) needlessly. Default (no flag) = full regen,
// the path to take after editing policy-content.ts.
const onlyMissing = process.argv.includes('--only-missing')

/** One translator per locale, memoized — identical strings (contact lines) hit once. */
function makeTranslator(locale: string) {
  const cache = new Map<string, string>()
  return async (s: string): Promise<string> => {
    const hit = cache.get(s)
    if (hit !== undefined) return hit
    const { text } = await deepl.translate(s, locale, 'en')
    cache.set(s, text)
    return text
  }
}

async function translateDoc(
  doc: PolicyDoc,
  tr: (s: string) => Promise<string>,
): Promise<LocalizedDoc> {
  const title = await tr(doc.title)
  const sections: LocalizedDoc['sections'] = []
  for (const sec of doc.sections) {
    const paragraphs: string[] = []
    for (const p of sec.paragraphs) paragraphs.push(await tr(p))
    sections.push(sec.heading ? { heading: await tr(sec.heading), paragraphs } : { paragraphs })
  }
  return { title, sections }
}

/** EN entry = the original, stripped to LocalizedDoc shape (drop `slug`). */
function stripDoc(doc: PolicyDoc): LocalizedDoc {
  return {
    title: doc.title,
    sections: doc.sections.map((s) =>
      s.heading ? { heading: s.heading, paragraphs: s.paragraphs } : { paragraphs: s.paragraphs },
    ),
  }
}

async function main() {
  const policyOut: Record<string, Record<string, LocalizedDoc>> = {
    [DEFAULT_LOCALE]: Object.fromEntries(slugs.map((s) => [s, stripDoc(POLICIES[s])])),
  }
  const aboutOut: Record<string, { title: string; paragraphs: string[] }> = {
    [DEFAULT_LOCALE]: { title: ABOUT.title, paragraphs: [...ABOUT.paragraphs] },
  }

  // For --only-missing, load the committed translations to reuse where complete.
  let priorPolicy: Record<string, Record<string, LocalizedDoc>> = {}
  let priorAbout: Record<string, { title: string; paragraphs: string[] }> = {}
  if (onlyMissing) {
    const mod = await import('../src/lib/policy-content-i18n')
    priorPolicy = mod.POLICY_I18N as unknown as typeof priorPolicy
    priorAbout = mod.ABOUT_I18N as unknown as typeof priorAbout
  }

  for (const locale of targets) {
    // Reuse an existing locale only if it carries every doc + about at the
    // current section shape — a shape mismatch means policy-content.ts moved on
    // and this locale must be re-translated even under --only-missing.
    const pDocs = priorPolicy[locale]
    const pAbout = priorAbout[locale]
    const complete =
      onlyMissing &&
      pDocs &&
      pAbout &&
      slugs.every((s) => pDocs[s]?.sections?.length === POLICIES[s].sections.length) &&
      pAbout.paragraphs?.length === ABOUT.paragraphs.length
    if (complete) {
      process.stderr.write(`keeping ${locale} (already translated)\n`)
      policyOut[locale] = pDocs
      aboutOut[locale] = pAbout
      continue
    }
    process.stderr.write(`translating ${locale}…\n`)
    const tr = makeTranslator(locale)
    const docs: Record<string, LocalizedDoc> = {}
    for (const slug of slugs) docs[slug] = await translateDoc(POLICIES[slug], tr)
    policyOut[locale] = docs
    const paragraphs: string[] = []
    for (const p of ABOUT.paragraphs) paragraphs.push(await tr(p))
    aboutOut[locale] = { title: await tr(ABOUT.title), paragraphs }
  }

  const header = `// GENERATED by scripts/translate-policies.ts — DO NOT EDIT BY HAND except
// for reviewed accuracy fixes. English is the binding original (docs/00 D18);
// non-EN entries are DeepL machine translations, reviewed once. Regenerate:
//   set -a; source .env.local; set +a; npx tsx scripts/translate-policies.ts
import type { Locale } from './locales'
import type { PolicyDoc } from './policy-content'

export interface LocalizedDoc {
  title: string
  sections: { heading?: string; paragraphs: string[] }[]
}

export const POLICY_I18N: Record<Locale, Record<PolicyDoc['slug'], LocalizedDoc>> =
${JSON.stringify(policyOut, null, 2)}

export const ABOUT_I18N: Record<Locale, { title: string; paragraphs: string[] }> =
${JSON.stringify(aboutOut, null, 2)}
`

  const outPath = path.join(process.cwd(), 'src/lib/policy-content-i18n.ts')
  writeFileSync(outPath, header)
  process.stderr.write(`\nwrote ${outPath}\n`)
}

main().catch((e) => {
  process.stderr.write(String(e) + '\n')
  process.exit(1)
})
